### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by phillipkamps**

### CODE REVIEW

**Comment by Reuben-Davison** [comment]
Add has many relationships to Customer model

**Comment by sandisz-d734m37** [comment]
Hey add "has_many :invoices" after line 5 on the customer.rb file bro smfh 😔

**Review by sandisz-d734m37 — APPROVED** [review]
Stellar work! Keep it up

**Review by Reuben-Davison — COMMENTED** [review]
after adding the has many relationships, all looks good.

**Pull request merged**
